//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctopusCodesMultiVendor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OctopusCodesMultiVendorsEntities : DbContext
    {
        public OctopusCodesMultiVendorsEntities()
            : base("name=OctopusCodesMultiVendorsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<MemberShip> MemberShips { get; set; }
        public virtual DbSet<MemberShipVendor> MemberShipVendors { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrdersDetail> OrdersDetails { get; set; }
        public virtual DbSet<OrderStatu> OrderStatus { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<ForgetPassword> ForgetPasswords { get; set; }
        public virtual DbSet<AccountAddress> AccountAddresses { get; set; }
        public virtual DbSet<OrderAddress> OrderAddresses { get; set; }
        public virtual DbSet<VendorAddress> VendorAddresses { get; set; }
        public virtual DbSet<RajaOngkir_CityMapping> RajaOngkir_CityMapping { get; set; }
        public virtual DbSet<VendorPendingPayment> VendorPendingPayments { get; set; }
        public virtual DbSet<PaymentStatu> PaymentStatus { get; set; }
        public virtual DbSet<AccountPaymentInfo> AccountPaymentInfoes { get; set; }
        public virtual DbSet<VendorPaymentInfo> VendorPaymentInfoes { get; set; }
        public virtual DbSet<VendorPendingDelivery> VendorPendingDeliveries { get; set; }
        public virtual DbSet<MessageSenderType> MessageSenderTypes { get; set; }
        public virtual DbSet<MessageDetail> MessageDetails { get; set; }
        public virtual DbSet<MessageHeader> MessageHeaders { get; set; }
    }
}
