//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctopusCodesMultiVendor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderAddress
    {
        public System.Guid Id { get; set; }
        public string LineAddress1 { get; set; }
        public string LineAddress2 { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public int OrderId { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
