//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctopusCodesMultiVendor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorPendingPayment
    {
        public System.Guid PaymentOrderID { get; set; }
        public int VendorId { get; set; }
        public decimal MerchandiseAmount { get; set; }
        public decimal DeliveryFee { get; set; }
        public int OrderId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
