//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctopusCodesMultiVendor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorPendingDelivery
    {
        public System.Guid DeliveryOrderId { get; set; }
        public int VendorId { get; set; }
        public Nullable<System.DateTime> StartDeliveryDate { get; set; }
        public string EstimatedDeliveredDays { get; set; }
        public Nullable<System.DateTime> EstimatedDeliveredDate { get; set; }
        public int OrderId { get; set; }
        public string TrackingId { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
