//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Email {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Email() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Email", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Your bank account has been {0}&lt;/p&gt;.
        /// </summary>
        internal static string Acct_BankStatus_Content {
            get {
                return ResourceManager.GetString("Acct_BankStatus_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Request.
        /// </summary>
        internal static string Acct_BankStatus_Subject {
            get {
                return ResourceManager.GetString("Acct_BankStatus_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Your account has been {0}&lt;/p&gt;.
        /// </summary>
        internal static string Acct_Status_Content {
            get {
                return ResourceManager.GetString("Acct_Status_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Request.
        /// </summary>
        internal static string Acct_Status_Subject {
            get {
                return ResourceManager.GetString("Acct_Status_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;You received a new message from {0}:&lt;br&gt;&lt;p&gt;{1}&lt;/p&gt;&lt;/p&gt;&lt;p hidden id=&apos;id&apos;&gt;{2}&lt;/p&gt;.
        /// </summary>
        internal static string Cust_SendMsg_Content {
            get {
                return ResourceManager.GetString("Cust_SendMsg_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Message from {0}.
        /// </summary>
        internal static string Cust_SendMsg_Subject {
            get {
                return ResourceManager.GetString("Cust_SendMsg_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Click &lt;a href=&apos;{0}&apos;&gt;here&lt;/a&gt; to reset your password.&lt;/p&gt;.
        /// </summary>
        internal static string Forget_Pwd_Content {
            get {
                return ResourceManager.GetString("Forget_Pwd_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        internal static string Forget_Pwd_Subject {
            get {
                return ResourceManager.GetString("Forget_Pwd_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;You received a new order from {0}:&lt;br&gt;&lt;p&gt;Login to system to set the delivery information:{1}&lt;/p&gt;&lt;/p&gt;.
        /// </summary>
        internal static string NewOrder_Content {
            get {
                return ResourceManager.GetString("NewOrder_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You received new order.
        /// </summary>
        internal static string NewOrder_Subject {
            get {
                return ResourceManager.GetString("NewOrder_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been created and is currently pending our officer for processing..
        /// </summary>
        internal static string Register_NewAcct_Body {
            get {
                return ResourceManager.GetString("Register_NewAcct_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome user {0}.
        /// </summary>
        internal static string Register_NewAcct_Subject {
            get {
                return ResourceManager.GetString("Register_NewAcct_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been created and is currently pending our officer for processing. Once the account has been approved. Please update your bank information in profile to enjoy the full features of the website..
        /// </summary>
        internal static string Register_NewVendor_Body {
            get {
                return ResourceManager.GetString("Register_NewVendor_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome vendor {0}.
        /// </summary>
        internal static string Register_NewVendor_Subject {
            get {
                return ResourceManager.GetString("Register_NewVendor_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a payment to your account ending with: ******{0} with amount of {1}..
        /// </summary>
        internal static string UpdatePaymentPaid_Content {
            get {
                return ResourceManager.GetString("UpdatePaymentPaid_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Payment disbursed to you.
        /// </summary>
        internal static string UpdatePaymentPaid_Subject {
            get {
                return ResourceManager.GetString("UpdatePaymentPaid_Subject", resourceCulture);
            }
        }
    }
}
